albums_index:
    path:     /
    defaults: { _controller: GalleryBundle:Default:index }

_json_albums_index:
    path:     /json/albums
    defaults: { _controller: GalleryBundle:Json:allAlbums }
    methods: [GET]
    requirements:
        

_json_album:
    path:     /json/album/{albumId}
    defaults: { _controller: GalleryBundle:Json:albumPage }
    methods: [GET]
    requirements:
            albumId: \d+
        
_json_album_page:
    path:     /json/album/{albumId}/page/{pageId}
    defaults: { _controller: GalleryBundle:Json:albumPage }
    methods: [GET]
    requirements:
        albumId: \d+
        pageId: \d+
